# Generated by Django 2.0.6 on 2019-06-04 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLeavingMessag',
            new_name='UserLeavingMessage',
        ),
    ]
